<?php
//邮件发送设置
$mCfg['SendMail']['Module']=0;
$mCfg['SendMail']['FromEmail']='sendmail@ly200.com';
$mCfg['SendMail']['FromName']='广州联雅网络科技有限公司';
$mCfg['SendMail']['Smtp']='';
$mCfg['SendMail']['Port']='25';
$mCfg['SendMail']['Email']='';
$mCfg['SendMail']['Password']='';
?>